version: '3'
services:
  minitwit:
    build: . # build the image from the Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development #Ensure that locally run env is Development. Fix found here: https://oneuptime.com/blog/post/2026-01-25-docker-compose-development-environments/view & here https://learn.microsoft.com/en-us/aspnet/core/fundamentals/environments?view=aspnetcore-10.0
    ports:
      - "8080:8080"
    volumes:
      - /minitwit/data:/app/Data  # mount database folder on vm to : our workdir in Dockerfile is /app, and the rest need to match our connectionstring

  prometheus:
    build: 
      dockerfile: ./Dockerfile
      context: ./monitoring/prometheus
    image: prometheus_image
    container_name: prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"
    

  grafana:
    build: 
      dockerfile: ./Dockerfile
      context: ./monitoring/grafana
    image: grafana_image
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana

volumes:
  grafana-storage: {} 

#Inspiration/guide: https://medium.com/@Shamimw/docker-a-complete-tutorial-part3-docker-compose-2e3b2f568a6f
