{
 "title": "Log-Dashboard",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  { "title": "Service logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "MiniTwit Logs",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=\"minitwit_minitwit\"} |= ``"
    }
   ]
  },
  {
   "title": "Grafana Logs",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service=\"minitwit_grafana\"} |= ``"
    }
   ]
  },
  {
   "title": "Alloy logs",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service=\"minitwit_alloy\"} |= ``"
    }
   ]
  },
  {
   "title": "Promethues logs",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service=\"minitwit_prometheus\"} |= ``"
    }
   ]
  },
  {
   "title": "Caddy logs",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service=\"minitwit_caddy\"} |= ``"
    }
   ]
  },
  {
   "title": "Loki Logs",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service=\"minitwit_loki\"} |= ``"
    }
   ]
  },
  { "title": "Node logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Leader logs",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{node=\"minitwit-swarm-leader\"} |= ``"
    }
   ]
  },
  {
   "title": "Manager0 Logs",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{node=\"minitwit-swarm-manager-0\"} |= ``"
    }
   ]
  },
  {
   "title": "Manager1 Logs",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{node=\"minitwit-swarm-manager-1\"} |= ``"
    }
   ]
  }
 ]
}