# -*- mode: ruby -*-
# vi: set ft=ruby :
# editied Vagrantfile from: https://github.com/itu-devops/flask-minitwit-mongodb.git && https://github.com/itu-devops/itu-minitwit-ci/blob/master/Vagrantfile

Vagrant.configure("2") do |config|
    config.vm.box = "bento/ubuntu-22.04"
    config.vm.network "forwarded_port", guest: 80, host: 8080
    config.vm.synced_folder "./", "/vagrant_data"

    config.vm.provider "virtualbox" do |vb|
      vb.gui = true
      vb.memory = "1024"


    config.vm.provision "shell", inline: <<-SHELL
      # The following addresses an issue in DO's Ubuntu images, which still contain a lock file
      sudo fuser -vk -TERM /var/lib/apt/lists/lock
      sudo apt-get update

      if ! command -v docker >/dev/null 2>&1
      then 
        echo "Installing docker"
      # Add Docker's official GPG key: (from session02 PREP)
        sudo apt-get install -y ca-certificates curl
        sudo install -y -m 0755 -d /etc/apt/keyrings #-d only create if it does not exists.

        sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
        sudo chmod a+r /etc/apt/keyrings/docker.asc 

        # Add the repository to Apt sources:
        echo \
        "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu \
        $(. /etc/os-release && echo "${UBUNTU_CODENAME:-$VERSION_CODENAME}") stable" | \
        sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
        sudo apt-get update

        echo "Installing docker plugins"
        sudo apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
          echo -e "\nVerifying that docker works ...\n"

        docker run --rm hello-world
        docker rmi hello-world
      else
        echo "Docker already installed"
      fi


        echo -e "\nOpening port for minitwit ...\n"
        ufw allow 5000 && \
        ufw allow 22/tcp


        if ! grep -qF ". $HOME/.bashrc" $HOME/.bash_profile; then 
          echo "Adding to bash profile"
          echo ". $HOME/.bashrc" >> $HOME/.bash_profile
        else
          echo "Already added to bash profile"
        fi

        echo -e "\nConfiguring credentials as environment variables...\n"

        source $HOME/.bash_profile

        if ! grep -qF "cd /minitwit" ~/.bash_profile; then
          echo -e "\nSelecting Minitwit Folder as default folder when you ssh into the server...\n"
          echo "cd /minitwit" >> ~/.bash_profile
        else 
          echo "Already selected MiniTwit folder as default when ssh into the server"
        fi

        chmod +x /minitwit/deploy.sh

        echo -e "\nVagrant setup done ..."
        echo -e "minitwit will later be accessible at http://$(hostname -I | awk '{print $1}'):8080"    
   SHELL
  end
end