@startuml 

skinparam linetype polyline
actor User

frame "Deployment MiniTwit" {
    
    frame "Docker swarm custer" as cluster {
        port ":8080" as 8080m1
        port ":9090" as 9090
        port ":3000" as 3000

        node "<<node>> Swarm 'Leader'" as leader {
            port ":443" as 443
            port ":80" as 80
            component Grafana
            component Loki
            component Alloy as alloy-leader
            component Promethues
            component Caddy {
                portout "8080" as cad-out
            }
        }
        note right of leader : For simplicity of the \n diagram the all \n minitwit services are \n shown on nthe \n workers and managers

    circle "." as circle

    together {
        node "<<node x2>> Swarm Manager"  as manager1 {
            portin ":8080" as 8080m2
            component "MiniTwit" as minitwit-manager1
            component Alloy as alloy-manager1
        }
        node "<<node x2>>  Swarm Worker" as worker1 {
            portin ":8080" as 8080m4
            component MiniTwit as minitwit-worker1

            component Alloy as alloy-worker1
        }
    }
    
    }
    

    database Postgres {
    }
}

'We need to dobble checj how Caddy intercepts the request'
User --> 443 : Devbobs.tech <<HTTPS>> 
User --> 80
'User is redirected to 443'
80 --> 443 : redirect
User --> 3000
User --> 8080m1
User --> 9090


443 -[dotted]-> Caddy

cad-out --> circle

circle --> 8080m2
circle --> 8080m4
minitwit-manager1 --> Postgres
minitwit-worker1 --> Postgres


@enduml

