@startuml 

actor User



frame "Deployment MiniTwit" {


    node "<<node>> Swarm 'Leader'" {
        port 443
        port 80
        port 8080 as 8080m1
        port 9090
        port 3000

        component MiniTwit as minitwit_leader{
            portin ":8080" as min_1
        }
        component Caddy {
            portout "8080" as cad_out
        }
        component Grafana
        component Loki
        component Alloy as alloy_leader
        component Promethues
    }

    together {
        node "<<node>> Swarm Manager" as manager1 {
            portin ":8080" as 8080m2
            component MiniTwit as minitwit_manager1
            component Alloy as alloy_manager1
    
        }

        node "<<node>> Swarm Manager" as manager2 {
            portin ":8080" as 8080m3
            component MiniTwit as minitwit_manager2
            component Alloy as alloy_manager2
        }

        node "<<node>> Swarm Worker" as worker1 {
            portin ":8080" as 8080m4
            component MiniTwit as minitwit_worker1

            component Alloy as alloy_worker1
        }

        node "<<node>> Swarm Worker" as worker2 {
            portin ":8080" as 8080m5
            component MiniTwit as minitwit_worker2
            component Alloy as alloy_worker2
        }
    }
    

    database Postgres {

    }
}

'We need to dobble checj how Caddy intercepts the request'
User --> 443 : Devbobs.tech <<HTTPS>> 

@enduml

