version: '3'
services:    
  minitwit:
    image: ${DOCKER_USERNAME}/minitwitimage
    ports:
      - "8080:8080"
    volumes:
      - /minitwit/data:/app/Data  # mount database folder on vm to : our workdir in Dockerfile is /app, and the rest need to match our connectionstring

  prometheus:
    image: ${DOCKER_USERNAME}/minitwit-prometheus
    container_name: prometheus
    volumes:
      - prometheus_data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"
  
  alloy: 
    image: ${DOCKER_USERNAME}/minitwit-alloy
    container_name: alloy
    command: 
      - "run"
      - "/etc/alloy/config.alloy"
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock 
    depends_on:
      - loki    

  loki: 
    image: ${DOCKER_USERNAME}/minitwit-loki
    container_name: loki
    ports:
      - "3100:3100"
    volumes:
      - loki-data:/loki
    command: "--config.file=/etc/loki/loki.yml"

  grafana:
    image: ${DOCKER_USERNAME}/minitwit-grafana
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana

volumes:
  loki-storage: {}
  grafana-storage: {} 
  prometheus_data: {}

#Inspiration/guide: https://medium.com/@Shamimw/docker-a-complete-tutorial-part3-docker-compose-2e3b2f568a6f
