@startuml

cloud "DigitalOcean" {
  node "Droplet" {

    component "MiniTwit API" as minitwit {
      interface "GET /metrics" as minitwit_metrics
    }

    component "Prometheus" as prometheus {
      interface "GET /metrics" as prom_api
    }

    component "Grafana" as grafana
  }
  
  database "PostgreSQL" as db
}


cloud "DockerHub" {
  component "Repositories" {
      interface "powsdaws/minitwitimage" as mt_repo
      interface "powsdaws/minitwit-prometheus" as prom_repo
      interface "powsdaws/minitwit-grafana" as grafana_repo
  }
  
}

cloud "Github Actions" {
    [CI/CD]
    [Release]
    [Build & Test]
    [Runner]
}

actor Author

Author --> minitwit : HTTP requests
minitwit --> db : SQL queries

prometheus --> minitwit_metrics : scrape metrics
grafana --> prom_api : query metrics

[CI/CD] --> [Runner]
[Release] --> [Runner]
[Build & Test] --> [Runner]



@enduml

