#edited yaml from: https://github.com/itu-devops/itu-minitwit-ci/blob/master/.github/workflows/continous-deployment.yml
name: cicd

on:
  workflow_run:
    workflows: ["Build and Test"] #Consider if this should only run if a release has been made
    types: [completed]
  workflow_dispatch: #Allow manual trigger of workflow

jobs:
  build:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.event == 'push'}}
    runs-on: ubuntu-24.04 # matches version in droplets
    env:
        ConnectionStrings__DefaultConnection: ${{ secrets.CONNECTION_STRING }} #env for database

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push minitwitimage
        uses: docker/build-push-action@v6
        with:
          context: ./itu-minitwit
          file: ./itu-minitwit/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/minitwitimage:latest
          cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/minitwitimage:webbuildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/minitwitimage:webbuildcache,mode=max

      - name: Build and push Alloy image
        uses: docker/build-push-action@d08e5c354a6adb9ed34480a06d141179aa583294
        with:
          context: ./itu-minitwit/monitoring/alloy/
          file: ./itu-minitwit/monitoring/alloy/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/minitwit-alloy:latest
          cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/minitwit-alloy:webbuildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/minitwit-alloy:webbuildcache,mode=max

      - name: Build and push Loki image
        uses: docker/build-push-action@d08e5c354a6adb9ed34480a06d141179aa583294
        with:
          context: ./itu-minitwit/monitoring/loki/
          file: ./itu-minitwit/monitoring/loki/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/minitwit-loki:latest
          cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/minitwit-loki:webbuildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/minitwit-loki:webbuildcache,mode=max

      - name: Build and push Promethues image
        uses: docker/build-push-action@v6
        with:
          context: ./itu-minitwit/monitoring/prometheus/
          file: ./itu-minitwit/monitoring/prometheus/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/minitwit-prometheus:latest
          cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/minitwit-prometheus:webbuildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/minitwit-prometheus:webbuildcache,mode=max

      - name: Build and push Grafana image
        uses: docker/build-push-action@v6
        with:
          context: ./itu-minitwit/monitoring/grafana/
          file: ./itu-minitwit/monitoring/grafana/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/minitwit-grafana:latest
          cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/minitwit-grafana:webbuildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/minitwit-grafana:webbuildcache,mode=max

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}


      - name: Copy stack file
        run: >
          scp -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ./itu-minitwit/infrastructure/docker_swarm/stack/minitwit_stack.yml $SSH_USER@$SSH_HOST:/root/
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          

      - name: Deploy to server
        # SSH in and deploy the stack
        run: >
          ssh $SSH_USER@$SSH_HOST
          -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no
          "DOCKER_USERNAME='$DOCKER_USERNAME' ConnectionStrings__DefaultConnection='$CONNECTION_STRING' docker stack deploy minitwit -c /root/minitwit_stack.yml"
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
          CONNECTION_STRING: ${{secrets.CONNECTION_STRING}}
