name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v6

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y graphviz default-jre texlive-luatex texlive-latex-extra texlive-xetex inkscape perl

      - name: Download PlantUML JAR
        run: |
          mkdir -p /opt/plantuml
          wget -O /opt/plantuml/plantuml.jar \
          https://github.com/plantuml/plantuml/releases/download/v1.2026.3/plantuml-1.2026.3.jar

      - name: Compile LaTeX document
        run: |
          cd report/src
          lualatex -interaction=nonstopmode -shell-escape --jobname=BSc_group_k main.tex
        env:
          PLANTUML_JAR: /opt/plantuml/plantuml.jar
          TEXINPUTS: ".:**:"

      - name: Recompile LaTeX document
        run: |
          cd report/src
          lualatex -interaction=nonstopmode -shell-escape --jobname=BSc_group_k main.tex
        env:
          PLANTUML_JAR: /opt/plantuml/plantuml.jar
          TEXINPUTS: ".:**:"

      - name: Print Folder Tree
        uses: jaywcjlove/github-action-folder-tree@main
        with:
          exclude: "node_modules|dist|.git|.husky"
          path: ./
          depth: 3

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v6
        with:
          name: BSc_group_k
          path: report/src/BSc_group_k.pdf
