name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v6

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y graphviz default-jre texlive-luatex texlive-latex-extra inkscape

      - name: Download PlantUML JAR
        run: |
          mkdir -p /opt/plantuml
          wget -O /opt/plantuml/plantuml.jar https://sourceforge.net/projects/plantuml/files/plantuml.jar/download

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v4
        with:
          root_file: report/src/main.tex
          latexmk_use_lualatex: true
          args: -shell-escape
        env:
          PLANTUML_JAR: /opt/plantuml/plantuml.jar

      - name: Commit and push PDF
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add main.pdf
          git commit -m "Build LaTeX document with PlantUML" || true
          git push
