# Taken from BDSA course: https://github.com/ITU-BDSA2024-GROUP15/Chirp/blob/main/.github/workflows/release.yml

name: Release

on:
  workflow_run:
    workflows: ["Build and Test"]
    types: [completed]
  workflow_dispatch: #Allow manual trigger of workflow


jobs:
  build:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-24.04 # matches version in droplets

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore itu-minitwit

    - name: Set realease tag
      run: echo "TAG=0.0.${GITHUB_RUN_NUMBER}" >> $GITHUB_ENV

    - name: Build
      run: dotnet build itu-minitwit --no-restore
  
    - name: Setup
      uses: actions/setup-dotnet@v4
      with:
          dotnet-version: 8.0.x

    - name: Install 7-Zip
      run: sudo apt-get update && sudo apt-get install -y p7zip-full

    - name: Build Linux
      shell: bash
      run: |
          release_name="App-$TAG-linux-x64"

          dotnet publish itu-minitwit/src/MiniTwit.Web/MiniTwit.Web.csproj --framework net8.0 --runtime linux-x64 -c Release -o "Linux-release" -p:PublishSingleFile=true
          
          7z a -tzip "MiniTwit-Linux-release.zip" "Linux-release"

          rm -r Linux-release

    - name: Build MacOS
      shell: bash
      run: |
          release_name="App-$TAG-osx-x64"

          dotnet publish itu-minitwit/src/MiniTwit.Web/MiniTwit.Web.csproj --framework net8.0 --runtime osx-x64 -c Release -o "MacOS-release" -p:PublishSingleFile=true
          
          7z a -tzip "MiniTwit-MacOS-release.zip" "MacOS-release"

          rm -r MacOS-release


    - name: Build Windows
      shell: bash
      run: |
          release_name="App-$TAG-win-x64"

          dotnet publish itu-minitwit/src/MiniTwit.Web/MiniTwit.Web.csproj --framework net8.0 --runtime win-x64 -c Release -o "Windows-release" -p:PublishSingleFile=true
          
          7z a -tzip "MiniTwit-Windows-release.zip" "./Windows-release/*"

          rm -r Windows-release

    - name: Release
      uses: softprops/action-gh-release@v2
      with:
          files: |
           MiniTwit-Linux-release.zip
           MiniTwit-MacOS-release.zip
           MiniTwit-Windows-release.zip
            
          repo-token: ${{ secrets.GITHUB_TOKEN }}
